### PR TITLE
Include base fields, simplify logic.

### PR DESCRIPTION
**Pull request by mglaman**
Here are some improvements. Base fields were missing and only FieldConfig displaying.

See attached result

download

### CODE REVIEW

**Comment by mglaman** [comment]
download 1

Here's progress with few more commits. Needs better handling for empty target bundles.

**Comment by mglaman** [comment]
download 5

Here is the final tidbit. Pretty much maps out the Drupal Commerce ERD perfectly.

**Comment by andypost** [comment]
somehow someone needs to roll new release @nabiyllin

**Comment by mbodalova** [comment]
1.module doesn't have description and link to the admin page with diagrams
2. not clear about color lines which show relationships. I thought they have to connect cell and entity. Or it is never minded here?

**Pull request merged**
